language: node_js
node_js:
- 8
script:
- yarn build
deploy:
  provider: heroku
  local_dir: build
  skip_cleanup: true
  api_key:
    secure: QPik9mIqGJR1EcFDcRcMhvgcmw4XrbO8c2AQCkqNp194mn1jKG8KezQWeHu79aevU36uNaLwXhTiPE4ZZGyBidMbfNKTs0SmlJn6XZPRBOKl8518tX0S4Iz5JvX8OGu2izQN2cvHh0C3ZJrUFurKxbIhmxGJXSnAaN4ffixgQQ2t9OYYaPR9O2dzLUXbmxGpJPN6HtlUTobcn4ClcZgX9BmBm996mndlgbwRX5VFGiKa9iqi8XGQnMB8E37T43GEZyfEjVVPJIWfVKbOWPaIOgzsj+GWXbmlYdOn1mcHECPi8YGxdceSEzVmjpHY8EMcucKb7PwlWFglvC3RDSvGg937qhpXsq6rbUJmsVaMMf63/8nhsLKkHdiQ9gvJeMtg7p3qnlOESYzqlbMCYPy+jJ1oQnEUc9sGZhe1BArt51YyAJz10NUC1hACJeuo75a8uWGxSXF6etPZBupQ6rnXqq8sRQZiFgF+T5MPLnbhUURU7H9QS5W9fjZaRyC89O1P/s6sF152HK7FdFlVs3jkcg2vZHkDhIHn4l80xHiza/swJfcTW3SUdZILB0W3WNrA2B2RXm/nNfccEfhuJDUQUN2ULWNT9ZP/jra4hmx5Wcqk3sHDEWjFE0ToNxI5Q8HZOzF4E4wc6ZXpIXoo6SNoj3ympndyTGR3vv7vUauAKms=
  app:
    master: hello-heroku-ts
